# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Laura Sans Comerma
title: Bioinformatics Engineering Graduate 
email: laurasansc@gmail.com
website: https://laurasansc.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: laurasansc
github_username:  laurasansc
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: laurasansc
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/laura_fotocarnet.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello World!

  My name is Laura. I am a Bioinformatics graduate with focus on working in deploying production level software for academic and industry research, and clinical use. During my masters program I have mainly worked with statistics and machine learning and deep learning courses. I am an ambitious person that thrives in multidisciplinary and diverse teams.

content:
  #- title: Experience # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: top-middle
  #      title: Super awesome project
  #      link: github.com/sproogen
  #      link_text: Project Website
  #      additional_links:
  #        - title:  sproogen/modern-resume-theme
  #          icon: fab fa-github
  #          url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #      quote: >
  #        This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #      description: | # this will include new lines to allow paragraphs
  #        I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bioinformatics Engineer
        link: biolib.com
        # link_text: boringcompany.com
        sub_title: BioLib
        caption: February 2022 - Present
        quote: > 
          Copenhagen, Denmark
        description: | # this will include new lines to allow paragraphs
            Developing and deploying production level bioinformatics software and models. My role involved mainly working with structural biology deep learning models such as AlphaFold, RoseTTAFold, among others. Technologies used: version control Git, DevOps using Docker, Python, R, Bash and basics of Javascript. 
      - layout: left
        title: Student Research Assistant
        link: biolib.com
        sub_title: BioLib
        caption: December 2019 - February 2022
        quote: >
          Copenhagen, Denmark
        description: |
          Research on bioinformatic software trends.

          Organizing hackathons: Copenhagen Bioinformatics hackathon 2020 (April 2020), Synthetic Health Data Hackathon 2020 (November 2020), Copenhagen Bioinformatics Hackathon 2021 (April 2021), protein edition. 
          
          Deploying production level bioinformatics software and models. Technologies used: Python, R, basics of Javascript.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Technical University of Denmark (DTU)
        caption: 2019 - 2022
        sub_title: MSc Bioinformatics and Systems Biology
        quote: >
          Kongens Lyngby, Denmark
        description: | # this will include new lines to allow paragraphs
          GPA: 10.65 (7-grade scale)
          
          Main courses: Introduction to Machine Learning and Data Mining, Deep Learning and Bayesian Machine Learning. Statistical Modelling and Applied Statistics. Systems biology, protein chemistry, NGS and compositional data analysis for genomics data. 
          
          Part of Society for Biological Engineering (SBE) student association.
      - layout: left
        title: Universitat Pompeu Fabra (UPF)
        caption: 2014 - 2018
        sub_title: BSc Human Biology
        quote: >
          Barcelona, Spain
        description: | # this will include new lines to allow paragraphs
          GPA: 7.85 ( 0 to 10 scale)
          
          Main courses: Cell biology, biochemistry and molecular biology, chemistry of drugs, structural biology and bioinformatics.

      - layout: left
        title: Radboud University (RU)
        caption: 2017 
        sub_title: BSc Biotechnology
        quote: >
          Nijmegen, The Netherlands 
        description: | # this will include new lines to allow paragraphs
          Semester abroad on the Erasmus+ Exchange Program Scholarship. 
          
          Main courses such as toxicology, functional genomics and neurobiology.
  - title: A Bit More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Biology, proteins, data science and software developing some of my other interests and hobbies are:
      - Knitting, painting, and other kinds of crafts
      - Playing basketball and horse riding
      - Cooking and eating


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
